import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
import { createAgentOutputSvg } from './agent-output-svg';

const client = new Client({
  name: 'retake-whiteboard-import-smoke-test',
  version: '0.1.0',
});

const transport = new StdioClientTransport({
  command: 'npm',
  args: ['run', '--silent', 'mcp'],
  cwd: process.cwd(),
  env: {
    RETAKE_WORKSPACE_DIR: process.env.RETAKE_WORKSPACE_DIR ?? '.retake-test',
  },
  stderr: 'pipe',
});

async function main(): Promise<void> {
  await client.connect(transport);

  await client.callTool({
    name: 'retake_reset_workspace',
    arguments: {},
  });

  const bindingResult = await client.callTool({
    name: 'retake_resolve_current_project',
    arguments: {},
  });
  const binding = readStructuredContent<{
    project: { projectId: string };
    board: { boardId: string };
  }>(bindingResult.structuredContent);

  await client.callTool({
    name: 'retake_set_project_binding',
    arguments: {
      projectId: binding.project.projectId,
      boardId: binding.board.boardId,
      codexProjectPath: process.cwd(),
      note: 'MCP import smoke test binding',
    },
  });
  const validationResult = await client.callTool({
    name: 'retake_validate_project_binding',
    arguments: {
      projectId: binding.project.projectId,
      boardId: binding.board.boardId,
      codexProjectPath: process.cwd(),
    },
  });
  const validation = readStructuredContent<{ ok: boolean }>(validationResult.structuredContent);
  if (!validation.ok) {
    throw new Error('Expected Codex project binding validation to pass');
  }

  const executionResult = await client.callTool({
    name: 'retake_create_execution',
    arguments: {
      projectId: binding.project.projectId,
      boardId: binding.board.boardId,
      capabilityId: 'image.generate',
      adapter: 'mcp_agent',
      inputBlockIds: ['block_brief'],
      agentHost: 'codex',
      triggerMode: 'manual_agent_session',
      skillId: 'image.general_concept',
      prompt: 'Import a real local file generated by an agent.',
    },
  });
  const execution = readStructuredContent<{ executionId: string }>(executionResult.structuredContent);

  const generatedPath = await writeAgentOutputSvg(execution.executionId);
  const assetResult = await client.callTool({
    name: 'retake_import_asset',
    arguments: {
      projectId: binding.project.projectId,
      sourcePath: generatedPath,
      sourceExecutionId: execution.executionId,
      kind: 'image',
      mimeType: 'image/svg+xml',
    },
  });
  const asset = readStructuredContent<{
    assetId: string;
    storageProvider: string;
    storageKey: string;
    previewUrl: string;
  }>(assetResult.structuredContent);

  const blockResult = await client.callTool({
    name: 'retake_create_image_result_block',
    arguments: {
      projectId: binding.project.projectId,
      boardId: binding.board.boardId,
      executionId: execution.executionId,
      assetId: asset.assetId,
      sourceBlockIds: ['block_brief'],
      title: 'Imported agent file result',
      body: 'This block was created from a file imported via retake_import_asset.',
    },
  });
  const block = readStructuredContent<{
    block: { blockId: string };
    snapshotSummary: { blocks: number; edges: number; assets: number; executions: number };
  }>(blockResult.structuredContent);

  const snapshotResult = await client.callTool({
    name: 'retake_get_board_snapshot',
    arguments: {
      projectId: binding.project.projectId,
      boardId: binding.board.boardId,
    },
  });
  const snapshot = readStructuredContent<{
    blocks: unknown[];
    assets: Array<{ assetId: string; storageProvider: string; storageKey: string; previewUrl: string }>;
    executions: Array<{
      status: string;
      agentHost?: string;
      triggerMode?: string;
      outputAssetIds: string[];
      outputBlockIds: string[];
    }>;
  }>(snapshotResult.structuredContent);

  await client.close();

  console.log(
    JSON.stringify(
      {
        generatedPath,
        bindingValidated: validation.ok,
        executionId: execution.executionId,
        asset,
        blockId: block.block.blockId,
        summary: block.snapshotSummary,
        snapshot: {
          blocks: snapshot.blocks.length,
          assets: snapshot.assets.length,
          latestAsset: snapshot.assets[0],
          latestExecution: snapshot.executions[0],
        },
      },
      null,
      2,
    ),
  );
}

async function writeAgentOutputSvg(executionId: string): Promise<string> {
  const outputDir = path.join(process.cwd(), 'tmp', 'agent-output');
  const outputPath = path.join(outputDir, `${executionId}.svg`);

  await mkdir(outputDir, { recursive: true });
  await writeFile(outputPath, createAgentOutputSvg(executionId), 'utf8');

  return outputPath;
}

function readStructuredContent<T>(value: unknown): T {
  if (!value || typeof value !== 'object') {
    throw new Error('Expected structuredContent object from MCP tool');
  }

  return value as T;
}

main().catch(async (error: unknown) => {
  await client.close().catch(() => undefined);
  console.error(error);
  process.exit(1);
});
