import type { BoardSnapshot, ExecutionRecord } from '../src/core/types';
import { createProviderImagePrompt, imageExecutionInputAssignments } from './image-execution-prompt';
import { createAssetFromDataUrl } from './local-store/asset-store';
import { readAssetAsDataUrl } from './local-store/asset-files';
import { resolveExecutionConnection } from './local-store/execution-provider-store';
import { failExecution, markExecutionRunning, updateImageResultBlock } from './local-store/execution-store';
import { loadSnapshot, saveSnapshot } from './local-store/snapshot-store';
import { createSerialTaskQueue } from './serial-task-queue';
import {
  VolcengineArkImageClient,
  type VolcengineArkImageConfig,
  type VolcengineArkImageResult,
} from './volcengine-ark-image-client';

interface ArkImageServiceDependencies {
  config?: VolcengineArkImageConfig;
  fetchImpl?: typeof fetch;
}

export async function startVolcengineArkImageGeneration(input: {
  projectId: string;
  boardId: string;
  executionId: string;
  connectionId: string;
}, dependencies: ArkImageServiceDependencies = {}): Promise<{
  snapshot: BoardSnapshot;
  execution: ExecutionRecord;
  completion: Promise<void>;
}> {
  const config = dependencies.config ?? await resolveArkImageConfig(input.connectionId);
  if (!config) throw new Error('Volcengine Ark Seedream is unavailable. Configure and test the connection in Retake Settings.');
  const current = await loadSnapshot(input.projectId, input.boardId);
  const queued = current.executions.find((candidate) => candidate.executionId === input.executionId);
  if (!queued || queued.status !== 'queued' || queued.adapter !== 'direct_api') {
    throw new Error(`Queued Direct API image execution not found: ${input.executionId}`);
  }
  if (queued.connectionId !== input.connectionId) {
    throw new Error(`Image execution connection mismatch: ${input.connectionId}`);
  }
  const started = await markExecutionRunning(input);
  const client = new VolcengineArkImageClient(config, dependencies.fetchImpl);
  const completion = executeArkImageRun(started.execution, client).catch(async (error) => {
    await failExecution({
      projectId: input.projectId,
      boardId: input.boardId,
      executionId: input.executionId,
      errorMessage: error instanceof Error ? error.message : 'Volcengine Ark image generation failed.',
    }).catch(() => undefined);
    throw error;
  });
  void completion.catch(() => undefined);
  return { ...started, completion };
}

async function executeArkImageRun(
  execution: ExecutionRecord,
  client: VolcengineArkImageClient,
): Promise<void> {
  const initial = await loadSnapshot(execution.projectId, execution.boardId);
  const inputAssignments = imageExecutionInputAssignments(execution);
  const referenceImages = await executionInputImages(initial, inputAssignments.map((assignment) => assignment.assetId));
  const size = requestedSize(execution);
  const enqueueWrite = createSerialTaskQueue();
  const results = await Promise.allSettled(execution.outputBlockIds.map(async (resultBlockId, index) => {
    await assertExecutionRunning(execution);
    const result = await client.generateImage({
      prompt: createProviderImagePrompt(execution, inputAssignments, {
        dialect: 'provider_api',
        variantIndex: index,
        variantCount: execution.outputBlockIds.length,
      }),
      images: referenceImages,
      size,
    });
    const generated = result.images[0];
    if (!generated) throw new Error('Volcengine Ark returned no image for the requested result.');
    await enqueueWrite(async () => {
      await assertExecutionRunning(execution);
      const asset = await createAssetFromDataUrl({
        projectId: execution.projectId,
        sourceExecutionId: execution.executionId,
        dataUrl: generated.dataUrl,
        fileName: `seedream-${index + 1}.jpg`,
        kind: 'image',
        width: generated.width,
        height: generated.height,
      });
      await recordProviderResult(execution, result, index);
      await updateImageResultBlock({
        projectId: execution.projectId,
        boardId: execution.boardId,
        executionId: execution.executionId,
        assetId: asset.assetId,
        resultBlockId,
        title: execution.outputBlockIds.length > 1 ? `Seedream result ${index + 1}` : 'Seedream result',
        body: 'Generated by Seedream through Volcengine Ark.',
      });
    });
  }));
  const failed = results.find((result): result is PromiseRejectedResult => result.status === 'rejected');
  if (failed) {
    throw failed.reason instanceof Error
      ? failed.reason
      : new Error('Volcengine Ark image generation failed for one or more candidates.');
  }
}

async function executionInputImages(snapshot: BoardSnapshot, assetIds: readonly string[]): Promise<string[]> {
  const uniqueAssetIds = [...new Set(assetIds)];
  for (const assetId of uniqueAssetIds) {
    if (!snapshot.assets.some((asset) => asset.assetId === assetId && asset.kind === 'image')) {
      throw new Error(`Seedream image input is missing from the board snapshot: ${assetId}`);
    }
  }
  return Promise.all(uniqueAssetIds.map((assetId) => readAssetAsDataUrl(snapshot.project.projectId, assetId)));
}

function requestedSize(execution: ExecutionRecord): string {
  const generation = isRecord(execution.params?.generation) ? execution.params!.generation : undefined;
  const width = finiteNumber(generation?.targetWidth);
  const height = finiteNumber(generation?.targetHeight);
  if (width && height) return `${Math.round(width)}x${Math.round(height)}`;
  const resolution = generation?.targetResolution;
  return resolution === '1K' || resolution === '2K' || resolution === '4K' ? resolution : '2K';
}

async function recordProviderResult(
  execution: ExecutionRecord,
  result: VolcengineArkImageResult,
  index: number,
): Promise<void> {
  const snapshot = await loadSnapshot(execution.projectId, execution.boardId);
  const persisted = snapshot.executions.find((candidate) => candidate.executionId === execution.executionId);
  if (!persisted || persisted.status !== 'running') throw new Error('Image execution is no longer running.');
  const arkImage = isRecord(persisted.params?.arkImage) ? persisted.params!.arkImage : {};
  const results = Array.isArray(arkImage.results) ? arkImage.results.filter(isRecord) : [];
  persisted.params = {
    ...persisted.params,
    arkImage: {
      ...arkImage,
      results: [...results, {
        index,
        ...(result.model ? { model: result.model } : {}),
        ...(result.usage ? { usage: result.usage } : {}),
      }],
    },
  };
  await saveSnapshot(snapshot);
}

async function assertExecutionRunning(execution: ExecutionRecord): Promise<void> {
  const snapshot = await loadSnapshot(execution.projectId, execution.boardId);
  const persisted = snapshot.executions.find((candidate) => candidate.executionId === execution.executionId);
  if (persisted?.status !== 'running') throw new Error('Image execution is no longer running.');
}

async function resolveArkImageConfig(connectionId: string): Promise<VolcengineArkImageConfig | undefined> {
  const connection = await resolveExecutionConnection(connectionId);
  if (!connection || connection.connectorId !== 'volcengine-ark') return undefined;
  return { apiKey: connection.apiKey, baseUrl: connection.baseUrl, model: connection.model };
}

function finiteNumber(value: unknown): number | undefined {
  return typeof value === 'number' && Number.isFinite(value) && value > 0 ? value : undefined;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === 'object' && !Array.isArray(value);
}
